In [1]:
import numpy as  np

In [8]:
Q = np.array([[0, 1, 1/2, 0, 0, 0], 
              [0, 0, 0, 1/2, 0, 0],
              [0, 0, 0, 1/2, 0, 0],
              [1, 0, 0, 0, 0, 1],
              [0, 0, 1/2, 0, 0, 0],
              [0, 0, 0, 0, 1, 0]])
for num in [10**i for i in range(6)]:
    newQ = np.linalg.matrix_power(Q, num)
    print(str(newQ @ np.ones(6)/ 6))

[0.25       0.08333333 0.08333333 0.33333333 0.08333333 0.16666667]
[0.27734375 0.14713542 0.14713542 0.26822917 0.09244792 0.06770833]
[0.23076975 0.15384573 0.15384573 0.30769234 0.07692325 0.0769232 ]
[0.23076923 0.15384615 0.15384615 0.30769231 0.07692308 0.07692308]
[0.23076923 0.15384615 0.15384615 0.30769231 0.07692308 0.07692308]
[0.23076923 0.15384615 0.15384615 0.30769231 0.07692308 0.07692308]
